<a href="https://colab.research.google.com/github/AI-Champ/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy.

In [ ]:
# NumPy stands for "Numerical Python".
# It is a popular open-source numerical computing library.
# It provides powerful tools and functions for handling large, multi-dimensional arrays and matrices.
# It has also a vast collection of mathematical functions to operate on these arrays efficiently.

# 3 main features of Numpy:

# Broadcasting: Arrays with different shapes can be operated together.

# Linear Algebra Operations: It provides linear algebra functions for operations like matrix multiplication, factorization, eigenvalues, and more.

# Integration with other Libraries: Can easily work with some other librarires, such as SciPy, pandas, scikit-learn, and TensorFlow.

In [ ]:
import numpy as np

In [ ]:
# Create one dimensional array.

np.array([1,2,3])

In [ ]:
# Create 2 dimensional array.
np.array([[1,2,3],[4,5,6]])

In [ ]:
# To check the dimension
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])
print(x.ndim)
print("-"*20)
print(y.ndim)

In [ ]:
# Create array from list
list1=[1,2,3]
list2=[[1,2,3],[4,5,6]]
x=np.array(list1)
y=np.array(list2)

print(x)
print("-"*20)
print(y)

In [ ]:
# Create array using arange functon
x=np.arange(10)
x

In [ ]:
x=np.arange(1,11)
x

In [ ]:
x=np.arange(1,11,2)
x

In [ ]:
# How can you check the shape of the array
list1=[1,2,3]
list2=[[1,2,3],[4,5,6]]
x=np.array(list1)
y=np.array(list2)

print(x)
print("-"*20)
print(y)

In [ ]:
x.shape

In [ ]:
y.shape

In [ ]:
np.shape(x)

In [ ]:
np.shape(y)

In [ ]:
# How can you reshape the array
x=np.arange(10)
x

In [ ]:
len(x)

In [ ]:
x.reshape(2,5)

In [ ]:
x

In [ ]:
x=x.reshape(2,5)
x

In [ ]:
# create one dimension array of values zero
x=np.zeros(5)
x

In [ ]:
# create multi dimension array of values zero
x=np.zeros((5,2))
x

In [ ]:
# create one dimension array of values one
x=np.ones(5)
x

In [ ]:
# create multi dimension array of values one
x=np.ones((3,4))
x

In [ ]:
# Create identity matrix as well
x=np.eye(3)
x

In [ ]:
# Linspace function
# Create an array of evenly spaced values within a specified range.
# It takes three parameters: start, stop, and num.

# Evenly spaced means, values are uniformly distributed.
# The difference between consecutive values is approximately same.

x = np.linspace(0,10,5)
print(x)

In [ ]:
x = np.linspace(1.5,6,9)
print(x)

In [ ]:
# Random function.
# If you want 3 random intergers of array between 1 tp 100.
np.random.randint(1,100,3)

In [ ]:
np.random.randint(90,200,5)

In [ ]:
np.random.randint(90,200,size=(2,3))

In [ ]:
# If you want to generate an array having standard normal distribution(mean=0 and stdv=1)
np.random.randn(3)

In [ ]:
np.random.randn(3,2)

In [ ]:
# If you want to generate an array of random numbers between 0 and 1.
np.random.rand(3)

In [ ]:
np.random.rand(3,2)

In [ ]:
# If you want to check minimum and maximum values in an array.
x=np.random.randint(1,100,size=(4,4))
x

In [ ]:
x.max()

In [ ]:
np.max(x)

In [ ]:
x.min()

In [ ]:
np.min(x)

In [ ]:
# If you want to check the index position of the minimum and maximum values in an array.
x

In [ ]:
x.argmax()

In [ ]:
np.argmax(x)

In [ ]:
x.argmin()

In [ ]:
np.argmin(x)

In [ ]:
# If you want to check the data type of the array.
x.dtype

In [ ]:
# Array indexing.
x=np.linspace(1,10,6)
x

In [ ]:
x[:]

In [ ]:
x[0]

In [ ]:
x[3:]

In [ ]:
x[:3]

In [ ]:
x=np.random.randint(1,100,size=(4,4))
x

In [ ]:
x[:]

In [ ]:
x[:,3]

In [ ]:
x[2,3]

In [ ]:
x[:2,2:]

In [ ]:
# Array conditional selection.
x

In [ ]:
x[x>40]

In [ ]:
x[x>=83]

In [ ]:
# Arithmetic operation.
x

In [ ]:
x+10

In [ ]:
y=[1,2,3]

In [ ]:
# x+y

In [ ]:
np.sin(x)

In [ ]:
np.sqrt(x)

In [ ]:
np.log(x)

In [ ]:
def func1(n):
  return n+5

func1(x)

# Randomly sampling.

In [173]:
# Randomly sample elements from an array.

my_array = np.array([1, 2, 3, 4, 5])

# Randomly sample 3 elements from the array without replacement
random_sample = np.random.choice(my_array, size=3, replace=False)

print(random_sample)

[3 5 2]


# Shuffle the elements.

In [174]:
# Shuffle the elements of an array.

my_array = np.array([1, 2, 3, 4, 5])

np.random.shuffle(my_array)

print(my_array)

[5 3 4 1 2]


# Transpose.

In [175]:
# Transpose an array.

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*30)

transposed_array = np.transpose(my_array)

print(transposed_array)

[[1 2 3]
 [4 5 6]]
------------------------------
[[1 4]
 [2 5]
 [3 6]]


# Concatenate

In [176]:
# Concatenate arrays along a specified axis.

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate the arrays along the 0th axis (default)
concatenated_array = np.concatenate((array1, array2))

print(concatenated_array)

[1 2 3 4 5 6]


In [177]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print('-'*40)
print(array2)
print('-'*40)

# Concatenate along axis 0 (rows)
concatenated_rows = np.concatenate((array1, array2), axis=0)

# Concatenate along axis 1 (columns)
concatenated_columns = np.concatenate((array1, array2), axis=1)

print("Concatenated along rows (axis 0):")
print(concatenated_rows)
print('-'*40)

print("Concatenated along columns (axis 1):")
print(concatenated_columns)

[[1 2]
 [3 4]]
----------------------------------------
[[5 6]
 [7 8]]
----------------------------------------
Concatenated along rows (axis 0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------------------------------
Concatenated along columns (axis 1):
[[1 2 5 6]
 [3 4 7 8]]


# Split

In [178]:
# Split an array into multiple sub-arrays.
my_array = np.array([1, 2, 3, 4, 5, 6])

# Split the array into three sub-arrays
sub_arrays = np.split(my_array, 3)

print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [179]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array at indices 2 and 6
sub_arrays = np.split(my_array, [2, 6])

print(sub_arrays)

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


# Mean

In [180]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the mean of the array
mean_value = np.mean(my_array)

print(mean_value)

3.0


In [181]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the mean along axis 0 (mean of each column)
mean_axis0 = np.mean(my_array, axis=0)

print("Mean along axis 0 (column-wise):")
print(mean_axis0)
print('-'*40)

# Calculate the mean along axis 1 (mean of each row)
mean_axis1 = np.mean(my_array, axis=1)

print("Mean along axis 1 (row-wise):")
print(mean_axis1)


[[1 2 3]
 [4 5 6]]
----------------------------------------
Mean along axis 0 (column-wise):
[2.5 3.5 4.5]
----------------------------------------
Mean along axis 1 (row-wise):
[2. 5.]


# Median

In [182]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the median of the array
median_value = np.median(my_array)

print(median_value)

3.0


In [183]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the median along axis 0 (median of each column)
median_axis0 = np.median(my_array, axis=0)

print("median along axis 0 (column-wise):")
print(median_axis0)
print('-'*40)

# Calculate the median along axis 1 (median of each row)
median_axis1 = np.median(my_array, axis=1)

print("median along axis 1 (row-wise):")
print(median_axis1)


[[1 2 3]
 [4 5 6]]
----------------------------------------
median along axis 0 (column-wise):
[2.5 3.5 4.5]
----------------------------------------
median along axis 1 (row-wise):
[2. 5.]


# Standard deviation.

In [185]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the standard deviation of the array
std_value = np.std(my_array)

print(std_value)

1.4142135623730951


In [184]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the standard deviation along axis 0 (standard deviation of each column)
std_axis0 = np.std(my_array, axis=0)

print("standard deviation along axis 0 (column-wise):")
print(std_axis0)
print('-'*40)

# Calculate the standard deviation along axis 1 (standard deviation of each row)
std_axis1 = np.std(my_array, axis=1)

print("standard deviation along axis 1 (row-wise):")
print(std_axis1)


[[1 2 3]
 [4 5 6]]
----------------------------------------
standard deviation along axis 0 (column-wise):
[1.5 1.5 1.5]
----------------------------------------
standard deviation along axis 1 (row-wise):
[0.81649658 0.81649658]


# Variance

In [186]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the variance of the array
variance_value = np.var(my_array)

print(variance_value)

2.0


In [187]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the variance along axis 0 (variance of each column)
variance_axis0 = np.var(my_array, axis=0)


print("Variance along axis 0 (column-wise):")
print(variance_axis0)
print('-'*40)

# Calculate the variance along axis 1 (variance of each row)
variance_axis1 = np.var(my_array, axis=1)
print("Variance along axis 1 (row-wise):")
print(variance_axis1)

[[1 2 3]
 [4 5 6]]
----------------------------------------
Variance along axis 0 (column-wise):
[2.25 2.25 2.25]
----------------------------------------
Variance along axis 1 (row-wise):
[0.66666667 0.66666667]


# Sum

In [188]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the sum of the array
sum_value = np.sum(my_array)

print(sum_value)

15


In [189]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the sum along axis 0 (sum of each column)
sum_axis0 = np.sum(my_array, axis=0)



print("Sum along axis 0 (column-wise):")
print(sum_axis0)
print('-'*40)

# Calculate the sum along axis 1 (sum of each row)
sum_axis1 = np.sum(my_array, axis=1)

print("Sum along axis 1 (row-wise):")
print(sum_axis1)

[[1 2 3]
 [4 5 6]]
----------------------------------------
Sum along axis 0 (column-wise):
[5 7 9]
----------------------------------------
Sum along axis 1 (row-wise):
[ 6 15]


# Product

In [190]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the product of the array
prod_value = np.prod(my_array)

print(prod_value)

120


In [191]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the product along axis 0 (product of each column)
prod_axis0 = np.prod(my_array, axis=0)



print("product along axis 0 (column-wise):")
print(prod_axis0)
print('-'*40)

# Calculate the product along axis 1 (product of each row)
prod_axis1 = np.prod(my_array, axis=1)

print("product along axis 1 (row-wise):")
print(prod_axis1)

[[1 2 3]
 [4 5 6]]
----------------------------------------
product along axis 0 (column-wise):
[ 4 10 18]
----------------------------------------
product along axis 1 (row-wise):
[  6 120]


# Cumulative sum.

In [192]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the cumulative sum of the array
cumulative_sum = np.cumsum(my_array)

print(cumulative_sum)

[ 1  3  6 10 15]


In [193]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the cumulative sum along axis 0 (column-wise)
cumulative_sum_axis0 = np.cumsum(my_array, axis=0)


print("Cumulative sum along axis 0 (column-wise):")
print(cumulative_sum_axis0)
print('-'*40)

# Calculate the cumulative sum along axis 1 (row-wise)
cumulative_sum_axis1 = np.cumsum(my_array, axis=1)
print("Cumulative sum along axis 1 (row-wise):")
print(cumulative_sum_axis1)


[[1 2 3]
 [4 5 6]]
----------------------------------------
Cumulative sum along axis 0 (column-wise):
[[1 2 3]
 [5 7 9]]
----------------------------------------
Cumulative sum along axis 1 (row-wise):
[[ 1  3  6]
 [ 4  9 15]]


# Cumulative product.

In [194]:
my_array = np.array([1, 2, 3, 4, 5])

# Calculate the cumulative product of the array
cumulative_product = np.cumprod(my_array)

print(cumulative_product)

[  1   2   6  24 120]


In [195]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('-'*40)

# Calculate the cumulative product along axis 0 (column-wise)
cumulative_product_axis0 = np.cumprod(my_array, axis=0)


print("Cumulative product along axis 0 (column-wise):")
print(cumulative_product_axis0)
print('-'*40)


# Calculate the cumulative product along axis 1 (row-wise)
cumulative_product_axis1 = np.cumprod(my_array, axis=1)
print("Cumulative product along axis 1 (row-wise):")
print(cumulative_product_axis1)

[[1 2 3]
 [4 5 6]]
----------------------------------------
Cumulative product along axis 0 (column-wise):
[[ 1  2  3]
 [ 4 10 18]]
----------------------------------------
Cumulative product along axis 1 (row-wise):
[[  1   2   6]
 [  4  20 120]]


# Unique

In [196]:
my_array = np.array([1, 2, 3, 4, 2, 3, 5, 6, 1])

# Find the unique elements in the array
unique_elements = np.unique(my_array)

print(unique_elements)

[1 2 3 4 5 6]


The np.unique function sorts the unique elements in ascending order by default. If you want to preserve the original order of the elements, you can pass the return_index=True parameter to also get the indices of the unique elements.

In [197]:
my_array = np.array([1, 2, 3, 4, 2, 3, 5, 6, 1])
print(my_array)
print('-'*40)

# Find the unique elements and their indices in the array
unique_elements, indices = np.unique(my_array, return_index=True)

print("Unique elements:")
print(unique_elements)
print('-'*40)

print("Indices of unique elements:")
print(indices)

[1 2 3 4 2 3 5 6 1]
----------------------------------------
Unique elements:
[1 2 3 4 5 6]
----------------------------------------
Indices of unique elements:
[0 1 2 3 6 7]


# Argsort

In [198]:
my_array = np.array([10, 5, 8, 2, 3])

# Get the indices that would sort the array
sorted_indices = np.argsort(my_array)

print(sorted_indices)

[3 4 1 2 0]


In [199]:
# Then you can use this to sort the array.
sorted_array = my_array[sorted_indices]

print(sorted_array)

[ 2  3  5  8 10]


# Sort.

In [200]:
my_array = np.array([10, 5, 8, 2, 3])

# Sort the array in ascending order
sorted_array = np.sort(my_array)

print(sorted_array)

[ 2  3  5  8 10]


In [201]:
# For descending.
my_array = np.array([10, 5, 8, 2, 3])

# Sort the array in descending order
sorted_array_descending = np.sort(my_array)[::-1]

print(sorted_array_descending)

[10  8  5  3  2]


In [202]:
my_array = np.array([[5, 2, 3],
                     [8, 1, 4]])
print(my_array)
print('-'*40)

# Sort the array along axis 1 (row-wise)
sorted_array_axis1 = np.sort(my_array, axis=1)

print("Sorted array along axis 1 (row-wise):")
print(sorted_array_axis1)
print('-'*40)

# Sort the array along axis 0 (column-wise)
sorted_array_axis0 = np.sort(my_array, axis=0)
print("Sorted array along axis 0 (column-wise):")
print(sorted_array_axis0)

[[5 2 3]
 [8 1 4]]
----------------------------------------
Sorted array along axis 1 (row-wise):
[[2 3 5]
 [1 4 8]]
----------------------------------------
Sorted array along axis 0 (column-wise):
[[5 1 3]
 [8 2 4]]


# Where.

In [203]:
my_array = np.array([1, 2, 3, 4, 5])

# Find the indices where the elements are greater than 3
indices = np.where(my_array > 3)

print(indices)

(array([3, 4]),)


In [204]:
my_array = np.array([1, 2, 3, 4, 5])

# Assign -1 to elements that are less than or equal to 3
modified_array = np.where(my_array <= 3, -1, my_array)

print(modified_array)

[-1 -1 -1  4  5]


# Any.

In [205]:
my_array = np.array([1, 2, 3, 4, 5])

# Check if any element is greater than 3
result = np.any(my_array > 3)

print(result)

True


In [206]:
my_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Check if any element is even
result = np.any(my_array % 2 == 0)

print(result)

True


# All.

In [207]:
my_array = np.array([1, 2, 3, 4, 5])

# Check if all elements are greater than 0
result = np.all(my_array > 0)

print(result)


True


In [208]:
my_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Check if all elements are even
result = np.all(my_array % 2 == 0)

print(result)

False


# Matrix multiplication.

In [209]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print(result)

[[19 22]
 [43 50]]


In [210]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform matrix multiplication
result = np.dot(array1, array2)

print(result)

32


In [211]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.matmul(matrix1, matrix2)

print(result)

[[19 22]
 [43 50]]


In [212]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Perform matrix multiplication
result = np.matmul(array1, array2)

print(result)

32


# Covariance matrix.

In [213]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(data)
print('-'*40)

# Calculate the covariance matrix
cov_matrix = np.cov(data)

print(cov_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Calculate the correlation.

In [214]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Calculate the correlation
correlation = np.correlate(array1, array2)

print(correlation)

[130]


# Check for infinity value.

In [215]:
arr = np.array([1.0, np.inf, -np.inf, 2.0, np.nan])

# Check for infinity
is_inf = np.isinf(arr)

print(is_inf)

[False  True  True False False]


# Check for NaN value.

In [216]:
arr = np.array([1.0, np.inf, -np.inf, 2.0, np.nan])

# Check for infinity
is_nan = np.isnan(arr)

print(is_nan)

[False False False False  True]


# Save the array to a file.

In [217]:
arr = np.array([1, 2, 3, 4, 5])

# Save the array to a file
np.save('my_array.npy', arr)

In [218]:
# Load the array from the file
loaded_array = np.load('my_array.npy')

print(loaded_array)

[1 2 3 4 5]
